__init__.py 2023-07-28 14:04:49,498 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
__init__.py 2023-07-28 14:04:49,499 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

__init__.py 2023-07-28 14:04:53,499 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
__init__.py 2023-07-28 14:04:53,500 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\TeleBot2_for_deploy\venv\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

bot_file.py 2023-07-28 14:05:13,855 INFO Боту пришло сообщение: "USD RUR"
bot_file.py 2023-07-28 14:05:14,439 INFO Бот ответил: "1 USD = 90.02 RUR по курсу ЦБ"
bot_file.py 2023-07-28 14:05:15,272 INFO Боту пришло сообщение: "TRY RUR"
bot_file.py 2023-07-28 14:05:15,820 INFO Бот ответил: "1 TRY = 3.34 RUR по курсу ЦБ"
bot_file.py 2023-07-28 14:05:16,489 INFO Боту пришло сообщение: "EUR RUR"
bot_file.py 2023-07-28 14:05:16,838 INFO Бот ответил: "1 EUR = 100.22 RUR по курсу ЦБ"
bot_file.py 2023-07-28 14:05:17,367 INFO Боту пришло сообщение: "USD TRY"
bot_file.py 2023-07-28 14:05:17,700 INFO Бот ответил: "1 USD = 26.95 TRY по курсу ЦБ"
bot_file.py 2023-07-28 14:05:18,188 INFO Боту пришло сообщение: "EUR TRY"
bot_file.py 2023-07-28 14:05:18,513 INFO Бот ответил: "1 EUR = 30.0 TRY по курсу ЦБ"
bot_file.py 2023-07-28 14:05:40,076 INFO Боту пришло сообщение: "EUR RUR"
bot_file.py 2023-07-28 14:05:40,413 INFO Бот ответил: "1 EUR = 100.22 RUR по курсу ЦБ"
__init__.py 2023-07-28 14:05:55,078 ERROR Infinity polling: polling exited
__init__.py 2023-07-28 14:05:55,078 ERROR Break infinity polling
